#QR CODE BASE BUS FARE PAYMENT SYSTEM
name: busfare
description: qr code based bus fare payment system

publish_to: 'none' 

version: 1.0.2+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_ui_auth: ^1.1.8
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_ui_oauth_google: ^1.0.15
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.1.0
  firebase_dynamic_links: ^5.0.11
  qr_code_scanner: ^1.0.1
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
