// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzYUUlRINre6pfGPpAjMFBcOaJMrUYZI',
    appId: '1:563101035174:web:ff05b3b7a6235cee2b6267',
    messagingSenderId: '563101035174',
    projectId: 'bus-fare-qr',
    authDomain: 'bus-fare-qr.firebaseapp.com',
    storageBucket: 'bus-fare-qr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_58hJ9SwltswmhlikvqiuLN-Tz3Zh8_M',
    appId: '1:563101035174:android:719864e44b220f032b6267',
    messagingSenderId: '563101035174',
    projectId: 'bus-fare-qr',
    storageBucket: 'bus-fare-qr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zywsk3pU0oq32-OAeaf0q2TJ81HHC6k',
    appId: '1:563101035174:ios:a01c3a85ec63f8462b6267',
    messagingSenderId: '563101035174',
    projectId: 'bus-fare-qr',
    storageBucket: 'bus-fare-qr.appspot.com',
    androidClientId: '563101035174-grud6udgnt1gc9ab6mk6u0s9k5tjgeer.apps.googleusercontent.com',
    iosClientId: '563101035174-b5t9kq4lujqd7im03jv83eedo64tt9j9.apps.googleusercontent.com',
    iosBundleId: 'in.krishnavishwakarma.busfare',
  );
}
